# Generated by Django 5.2.1 on 2025-05-27 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='horario_fin',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='medico',
            name='horario_inicio',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='medico',
            name='intervalo_minutos',
            field=models.IntegerField(default=30),
        ),
    ]
