# Generated by Django 5.2.1 on 2025-05-27 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_medico_horario_fin_medico_horario_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='dias_atencion',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='horario_fin',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='horario_inicio',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='intervalo_minutos',
        ),
        migrations.CreateModel(
            name='DiaAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=10)),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
                ('intervalo_minutos', models.IntegerField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_atencion', to='gestion.medico')),
            ],
        ),
    ]
