# Generated by Django 5.2.1 on 2025-06-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_remove_paciente_email_remove_paciente_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='hora',
            field=models.CharField(max_length=5),
        ),
    ]
