# Generated by Django 5.2.1 on 2025-06-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_dianolaborable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaatencion',
            name='dia',
            field=models.IntegerField(choices=[(0, 'LUNES'), (1, 'MARTES'), (2, 'MIERCOLES'), (3, 'JUEVES'), (4, 'VIERNES'), (5, 'SABADO'), (6, 'DOMINGO')]),
        ),
    ]
