# Generated by Django 5.2.1 on 2025-06-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_diaatencion_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='estado',
            field=models.CharField(default='otorgado', max_length=20),
        ),
    ]
